"""add max_per_order to ticket types

Revision ID: 69998bc3433a
Revises: c2e85814f3fb
Create Date: 2026-06-12 23:04:41.716158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69998bc3433a'
down_revision: Union[str, Sequence[str], None] = 'c2e85814f3fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_types', sa.Column('max_per_order', sa.Integer(), nullable=False, server_default='4'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_types', 'max_per_order')
    # ### end Alembic commands ###
