"""add reservation_expiry_minutes to events

Revision ID: 726e43806d5a
Revises: 9d826124440b
Create Date: 2026-06-17 19:48:36.619366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '726e43806d5a'
down_revision: Union[str, Sequence[str], None] = '9d826124440b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('reservation_expiry_minutes', sa.Integer(), nullable=False, server_default='15'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'reservation_expiry_minutes')
    # ### end Alembic commands ###
