"""add event_id to tickets

Revision ID: c2e85814f3fb
Revises: 00e091df31c3
Create Date: 2026-06-10 15:40:39.317028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2e85814f3fb'
down_revision: Union[str, Sequence[str], None] = '00e091df31c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('event_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'tickets', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'event_id')
    # ### end Alembic commands ###
